// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
  aws_app_analytics: 'enable',
  aws_cognito_identity_pool_id:
    'us-east-1:e7ac86fe-a833-47c6-850a-7ecd18bde864',
  aws_cognito_region: 'us-east-1',
  aws_mobile_analytics_app_id: 'c75a2e3f3e42419ab3c73ac5a87eab90',
  aws_mobile_analytics_app_region: 'us-east-1',
  aws_project_id: '0db1112f-11b3-4109-b790-d2cea7b0fa4e',
  aws_project_name: 'dbt-coach',
  aws_project_region: 'us-east-1',
  aws_resource_name_prefix: 'dbtcoach-mobilehub-875871872',
  aws_sign_in_enabled: 'enable',
  aws_user_files: 'enable',
  aws_user_files_s3_bucket: 'dbtcoach-userfiles-mobilehub-875871872',
  aws_user_files_s3_bucket_region: 'us-east-1',
  aws_user_pools: 'enable',
  aws_user_pools_id: 'us-east-1_8IKu6FeB5',
  aws_user_pools_web_client_id: '4nihtcg3nvr8jqveh3p7ead6q6',
};

// 'aws_user_files': 'enable',
//     'aws_user_files_s3_bucket': 'swasth-userfiles-mobilehub-1095358790',
//     'aws_user_files_s3_bucket_region': 'us-east-1',

export default awsmobile;
