# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "CoachingApp.xcodeproj")
    build_app(workspace: "CoachingApp.xcworkspace", scheme: "CoachingApp")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end
  lane :beta do
    match(
      type: "appstore",
      git_url: "ssh://swasth/v1/repos/swasth-apps-codesign"
    ) # match(type: "appstore") # more information: https://codesigning.guide
    increment_build_number(xcodeproj: "CoachingApp.xcodeproj")
    build_app(scheme: "CoachingApp")
    upload_to_testflight
    upload_symbols_to_bugsnag
  end
  lane :refresh_dsyms do
    download_dsyms(version: "2.0.2")     # Download dSYM files from iTC
    upload_symbols_to_bugsnag              # Upload them to Bugsnag
    clean_build_artifacts                  # Delete the local dSYM files
  end
end
